#ifndef QT_CALC_SETTINGS_HPP
#define QT_CALC_SETTINGS_HPP

#define SETTINGS_SAVE "SETTINGS_SAVE"
#define SETTINGS_SHOW_KEYPAD "SETTINGS_SHOW_KEYPAD"
#define SETTINGS_SHOW_BITTOGGLE "SETTINGS_SHOW_BITTOGGLE"
#define SETTINGS_SHOW_DOCK "SETTINGS_SHOW_DOCK"
#define SETTINGS_HISTORY "SETTINGS_HISTORY"
#define SETTINGS_HISTORY_LIMIT "SETTINGS_HISTORY_LIMIT"
#define SETTINGS_SIZE "SETTINGS_SIZE"
#define SETTINGS_DOCKPOS "SETTINGS_DOCKPOS"
#define SETTINGS_DOCK_TAB "SETTINGS_DOCK_TAB"

#endif //QT_CALC_SETTINGS_HPP
