#ifndef QCALC_SETTINGCONSTANTS_HPP
#define QCALC_SETTINGCONSTANTS_HPP

#define SETTING_KEY_PRECISION "_qcalc_precision_internal"
#define SETTING_DEFAULT_PRECISION 3322

#define SETTING_KEY_FORMATTING_PRECISION "_qcalc_precision_formatting"
#define SETTING_DEFAULT_FORMATTING_PRECISION 9

#define SETTING_KEY_ROUNDING "_qcalc_rounding_internal"
#define SETTING_DEFAULT_ROUNDING 0

#define SETTING_KEY_FORMATTING_ROUNDING "_qcalc_rounding_formatting"
#define SETTING_DEFAULT_FORMATTING_ROUNDING 0

#define SETTING_KEY_SYMBOLS_PRECISION "_qcalc_precision_symbols"
#define SETTING_DEFAULT_SYMBOLS_PRECISION 3322

#endif //QCALC_SETTINGCONSTANTS_HPP
