#ifndef QCALC_SETTINGCONSTANTS_HPP
#define QCALC_SETTINGCONSTANTS_HPP

#define SETTING_KEY_PRECISION "_qcalc_precision"
#define SETTING_DEFAULT_PRECISION 9

#define SETTING_KEY_ROUNDING "_qcalc_rounding"
#define SETTING_DEFAULT_ROUNDING 0

#endif //QCALC_SETTINGCONSTANTS_HPP
